# Generated by Django 4.1.3 on 2022-11-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='pub_date',
        ),
    ]
